### ISSUE TITLE
Scan entire directory doesn't work

### ISSUE THREAD

**Issue by rianquinn** [codingjoe/relint#12]
```
relint -c .relint.yml **
```

just returns:
```
relint: error: unrecognized arguments: <files and directories in my repo>
```

If I don't include the -c, I don't get this error, but I also don't see any output. It only works when I do
```
relint <path to specific file>
```

with a default config name

**Comment by codingjoe** [comment]
Thanks @rianquinn for bringing this issue to my attention. I think I have found the issue, could you please verify that my patch (#13) is solving the issue. Simply do
```
pip install -e git+https://github.com/codingjoe/relint.git@issues/12#egg=relint
```
and run your commands again and see if they pass.
Can't wait to get your feedback!
-Joe
