### ISSUE TITLE
Add verbosity levels

### ISSUE THREAD

**Issue by amureki** [codingjoe/relint#23]
In my usecase, I am defining rule with an extensive hint. While it might make sense to show it in majority of the cases, maybe sometimes in a known set of rules I just need to know which rule failed without the detailed description.
I could imagine it this way:

```
relint myfile.py

1>    myfile.py:12 relint rule name
2>    myfile.py:17 relint second rule name


~~~

relint myfile.py --verbose

1>    myfile.py:12 relint rule name
Hint: extensive rule description for multiple lines

2>    myfile.py:17 relint second rule name
Hint: another extensive rule description for multiple lines
```

**Comment by codingjoe** [comment]
Excellent idea @amureki. Go for it!
