### ISSUE TITLE
Crash on empty configuration

### ISSUE THREAD

**Issue by witekio-kwe** [codingjoe/relint#24]
```
Traceback (most recent call last):
  File "/path/bin/relint", line 8, in <module>
    sys.exit(main())
  File "/path/lib/python3.8/site-packages/relint.py", line 220, in main
    tests = list(load_config(args.config))
  File "/path/lib/python3.8/site-packages/relint.py", line 60, in load_config
    for test in yaml.safe_load(fs):
TypeError: 'NoneType' object is not iterable
```

Reproduction:
- create an empty file relint.yaml
- run with relint -c relint.yaml

**Comment by codingjoe** [comment]
Hi @witekio-kwe,

Thanks for reaching out. Yes, we expect the YAML to be a list. I believe we should output a human-readable error message.

I'll whip up something.

Cheers,
Joe

**Comment by codingjoe** [comment]
@witekio-kwe would you be so kind as to review #25? I'd just want to make sure that this will improve upon the issue you reported.

**Comment by witekio-kwe** [comment]
@codingjoe the better error message are a very nice improvement - thx for that.
But still it doesn't actually solve my problem.

We have a multi repository structure and using pre-commit in each of them, where relint is a integral part of it.
But for one of the many repository, we need to have **no** rules in this file, while all the other repos do have at least one rule.
I kind of helped myself with create a dummy rule for this particular repo, but that doesn't look well IMO.
From my perspective I'd expect that relint just returns with exit 0 if there are no rules configured - currently I will always get a non zero code in this special case

**Comment by codingjoe** [comment]
Aaah, I see. Interesting use case. I won't exit with an error, but emit a `UserWarning` instead. That won't result in a non-zero exit code, but still is verbose enough to suggest changes.

**Comment by witekio-kwe** [comment]
> Aaah, I see. Interesting use case. I won't exit with an error, but emit a `UserWarning` instead. That won't result in a non-zero exit code, but still is verbose enough to suggest changes.

ok, that would ofc work for me as well

**Comment by codingjoe** [comment]
@witekio-kwe release 1.3.2 ships with your fix :)
