### ISSUE TITLE
Output not showing up when running inside of bash script

### ISSUE THREAD

**Issue by El-Virus** [codingjoe/relint#77]
Calling relint inside of a shellscript will just only display the progress bar and return 0.

**Comment by codingjoe** [comment]
Hi @El-Virus,

This seems to be related to rich. As far as I understand, they always flush. Have you checked, if they maybe write parts of the output to stderr, not stdout?

If you have a sample script or a little more info, so I can reproduce the issue, I'd be happy to dig a little deeper.

Cheers,
Joe

**Comment by El-Virus** [comment]
I thought that it was relint itself that handled glob pattern extension, not bash. That was my issue, it was as easy as enabling globstar inside the script.
