### ISSUE TITLE
[Feature] Add global ignore file

### ISSUE THREAD

**Issue by mroy-seedbox** [codingjoe/relint#93]
While it is possible to exclude files using the regex in `filePattern`, that quickly becomes undesirable (not DRY) when there are dozens of rules applying to all files of a certain type _except certain files or paths_.

it would be good to add support for a `.relintignore` file, which would contain a list of regexes to ignore globally.

**Comment by mroy-seedbox** [comment]
**_Actually_**... this is no big deal! YAML anchors to the rescue! 🎉 

```
# Python patterns:
- name: ...
  pattern: ...
  filePattern: &python_pattern '...'
- name: ...
  pattern: ...
  filePattern: *python_pattern
- name: ...
  pattern: ...
  filePattern: *python_pattern
  
# SQL patterns:
- name: ...
  pattern: ...
  filePattern: &sql_pattern '...'
- name: ...
  pattern: ...
  filePattern: *sql_pattern
- name: ...
  pattern: ...
  filePattern: *sql_pattern
```

A `.relintignore` file would still be a bit cleaner (because file exclude patterns can get pretty messy), but it's just a nice-to-have at this point.

**Comment by codingjoe** [comment]
Hehe, yes, isn't ymal an amazing language. Between it and RegEx there is nothing you can't do 😊
